version: '3'

vars:
  WSL:
    sh: |
        if [ `uname -s` = "Linux" ]; then
          if grep -q "microsoft" <<< `uname -r`; then
            echo true
          else
            echo false
          fi
        else
          echo false
        fi
  EXE: bin/TinGrizzly{{if eq .WSL "true"}}.exe{{else}}{{exeExt}}{{end}}
  MAIN_CMD: ./cmd/TinGrizzly

tasks:
  default:
    cmds:
      - task -l
    silent: true

  run:
    desc: run the game
    deps: [build]
    cmds:
      -  ./{{.EXE}}

  test:
    desc: run all tests
    cmds:
      - go test ./... -cover -covermode atomic

  testv:
    desc: run all tests verbosely
    cmds:
      - go test ./... -cover -covermode atomic -v

  todo:
    desc: find all //TODO comments in the repo
    cmds:
      - grep -nr --exclude="Taskfile.yml" --exclude-dir=".git" "//TODO" . 
    
  build:
    desc: build executable to {{.EXE}}
    cmds:
      - task: build-{{ if eq .WSL "true" }}wsl{{else}}all{{end}}
    sources:
      - ./**/*.go
    generates:
      - ./{{.EXE}}

  build-all:
    cmds:
      - CGO_ENALBED=1 go build -v -o {{.EXE}} {{.MAIN_CMD}}

  build-wsl:
    cmds:
      - CC=x86_64-w64-mingw32-gcc GOOS=windows GOARCH={{ARCH}} CGO_ENABLED=1 go build -v -o {{.EXE}} {{.MAIN_CMD}} 
